name: E2E Tests

on: 
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress E2E Tests
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_host: localhost
          CYPRESS_port: 3000
        with:
          build: yarn run build
          start: yarn run start